apiVersion: batch/v1
kind: Job
metadata:
  name: charity-tests
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: charity-tests
          image: localhost/charity-tests:latest
          imagePullPolicy: Never
          command: ["/app/.venv/bin/python"]
          args: ["-m", "pytest", "-v", "--tb=short"]
          env:
            - name: API_BASE_URL
              value: "http://charity-api:4040"
            - name: TEST_USER_LOGIN
              valueFrom:
                secretKeyRef:
                  name: charity-tests-secret
                  key: TEST_USER_LOGIN
            - name: TEST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: charity-tests-secret
                  key: TEST_USER_PASSWORD
            - name: INVALID_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: charity-tests-secret
                  key: INVALID_USER_PASSWORD
