apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-api
  namespace: default
  labels:
    app: charity-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charity-api
  template:
    metadata:
      labels:
        app: charity-api
        version: v1
    spec:
      containers:
        - name: charity-api
          image: localhost/charity-api:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 4040
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          # Ресурсы для корректной работы метрик
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4040"
---
apiVersion: v1
kind: Service
metadata:
  name: charity-api
  namespace: default
  labels:
    app: charity-api
spec:
  selector:
    app: charity-api
  ports:
    - name: http
      protocol: TCP
      port: 4040
      targetPort: http
  type: ClusterIP
