name: Python Code Quality Checks


on:
  push:
  workflow_dispatch:

jobs:
  lock_file:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python and UV
        uses: ./.github/actions/setup

      - name: Generate/Check Lockfile
        run: uv lock --locked

  linting:
    runs-on: ubuntu-22.04
    needs: [lock_file]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python and UV
        uses: ./.github/actions/setup
      - name: Run Ruff Linter
        run: uvx ruff check .

  formatting:
    runs-on: ubuntu-22.04
    needs: [lock_file]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python and UV
        uses: ./.github/actions/setup
      - name: Check Ruff Formatting
        run: uvx ruff format --check .

  type_consistency:
    runs-on: ubuntu-22.04
    needs: [lock_file]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python and UV
        uses: ./.github/actions/setup
      - name: Run Pyright Type Checker
        run: uv run pyright .
